

CREATE TABLE TRANSMISSION(
	VT_MODET VARCHAR(20),
	PRIMARY KEY(VT_MODET)
) TYPE=INNODB;


CREATE TABLE VIRUS(
	VV_ABREV VARCHAR(10),
	VV_NOMV VARCHAR(30),
	VV_TYPEGENOME VARCHAR(5),
	VV_NOMFA VARCHAR(20),
	PRIMARY KEY(VV_ABREV)
) TYPE=INNODB;


CREATE TABLE VIRUS_TRANSMISSION(
	VVT_MODET VARCHAR(20) REFERENCES TRANSMISSION(VT_MODET),
	VVT_ABREVV VARCHAR(10) REFERENCES VIRUS(VV_ABREV)
) TYPE=INNODB;



