
CREATE TABLE MALADIE(
	MM_NOM_MALADIE VARCHAR(25),
	PRIMARY KEY(MM_NOM_MALADIE)
) TYPE=INNODB;


CREATE TABLE FACTEUR(
	MF_ABREV_FACTEUR VARCHAR(20),
	MF_NOM_FACTEUR VARCHAR(30),
	MF_TYPE_FACTEUR VARCHAR(10),
	PRIMARY KEY(MF_ABREV_FACTEUR)
) TYPE=INNODB;


CREATE TABLE APRORIGINE(
	MA_NOMM VARCHAR(25),
	MA_ABREVF VARCHAR(20),
	MA_SOUCHE VARCHAR(10),
	FOREIGN KEY(MA_NOMM) REFERENCES MALADIE(MM_NOM_MALADIE),
	FOREIGN KEY(MA_ABREVF) REFERENCES FACTEUR(MF_ABREV_FACTEUR)
) TYPE=INNODB;


