

CREATE TABLE RECENSEMENT(
    RR_ID       INT NOT NULL AUTO_INCREMENT,
    RR_NBRE		VARCHAR(3),
    RR_ANNEE	VARCHAR(4),
	PRIMARY KEY(RR_ID)
) TYPE=INNODB;



CREATE TABLE ZONE_OMS(
    RZ_LIBELLE		VARCHAR(40),
    RZ_POPULATION   VARCHAR(10),
	PRIMARY KEY(RZ_LIBELLE)
) TYPE=INNODB;


CREATE TABLE PAYS(
    RP_LIBELLE_ZO	 VARCHAR(40),
    RP_LIBELLE       VARCHAR(40),
	RP_POPULATION	 VARCHAR(10),
	FOREIGN KEY(RP_LIBELLE_ZO) REFERENCES ZONE_OMS(RZ_LIBELLE),
	PRIMARY KEY(RP_LIBELLE)
) TYPE=INNODB;


CREATE TABLE MALADIE(
	RM_ID       		INT NOT NULL AUTO_INCREMENT,
    RM_LIBELLE       	VARCHAR(40),
	RM_POPULATION		VARCHAR(10),
	RM_ID_RECENSEMENT	INT,
	RM_LIBELLE_PAYS		VARCHAR(40), 
	PRIMARY KEY(RM_ID),
	FOREIGN KEY(RM_ID_RECENSEMENT) REFERENCES RECENSEMENT(RR_ID),
	FOREIGN KEY(RM_LIBELLE_PAYS) REFERENCES PAYS(RP_LIBELLE)
) TYPE=INNODB;
